### ISSUE TITLE
Country list should be internationalized

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#184]
The country list for flag state should be internationalized. For example 'United States' is the English; 'Estados Unidos' is Spanish; 'États Unis' is French. If you can provide the localized lists for Spanish and French that would be awesome - but if not that's OK too - I can provide them.

**Comment by akaktus** [comment]
For now it works correctly. 
Spanish
![Simulator Screen Shot - iPhone 11 - 2020-08-06 at 15 30 56](https://user-images.githubusercontent.com/17438295/89532066-e199c100-d7f9-11ea-8630-ee7064536432.png)
French
![Simulator Screen Shot - iPhone 11 - 2020-08-05 at 17 02 49](https://user-images.githubusercontent.com/17438295/89532077-e65e7500-d7f9-11ea-8051-1842744caea6.png)
Country list doesn't need localization because it uses device local.
