### ISSUE TITLE
Cancel boarding

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#202]
When canceling a boarding the modal allows options of 'Cancel' and 'Go Back' - that should be 'Cancel Boarding' and 'Keep Editing' to avoid confusion.

**Comment by akaktus** [comment]
@Sheeri @am-MongoDB  If I change "Cancel" on "Cancel boarding" I will have alert that doesn't conform design. 
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-02 at 15 33 25](https://user-images.githubusercontent.com/17438295/91981538-ad022200-ed31-11ea-9509-0ef905af8f15.png) 
design:
![Screen Shot 2020-09-02 at 3 38 50 PM](https://user-images.githubusercontent.com/17438295/91982093-6c56d880-ed32-11ea-9556-1c245c9f7e8b.png)

This is due to the fact that "Cancel boarding" is too long and we don't have opportunity to place it in one line.
For now we have this alert 
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-02 at 15 34 37](https://user-images.githubusercontent.com/17438295/91981655-d622b280-ed31-11ea-8484-44283cf6b70e.png)
I propose leave it as is as. Please write your proposal or close this ticket.

**Comment by Sheeri** [comment]
I've asked Michael and he's OK with the 2 lines instead of left/right. Please change to the new longer phrases.
