### ISSUE TITLE
List of existing reports should show the most recent

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#323]
I'm seeing this list, even though searching reveals that there are more recent reports
![image](https://user-images.githubusercontent.com/14197449/94252419-d02c8580-ff1b-11ea-8eb2-d2c691083948.png)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by Sheeri** [comment]
I was not able to reproduce this issue. I ran into a similar issue because of the agency partition, but searching showed me boarding records from other partitions. If you have a particular environment and agency that is showing this, can you let me know the agency and environment names so I can reproduce?
