### ISSUE TITLE
Use device appearance if in-app dark mode not set

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#373]
**Describe the bug**
If "Dark Mode" is not set in the app settings, then the app should use the device-wide appearance setting to decider whether to render in light or dark mode.

**To Reproduce**
1. Set the device appearance to Dark Mode
1. Run the app with the in-app dark mode setting set to off

**Expected behavior**
App should render in dark mode

**Comment by evnik** [comment]
I'd like to work on this.
So, when this option is set to on and then set back to off, should the app enforce light mode, or follow the device appearance?

**Comment by Sheeri** [comment]
Hi!

So here's the thinking: the users may or may not be tech savvy. They might not know how to turn on dark mode on their device. So we assume if they have it turned on for their device, it's because they specifically turned it on. 

If not, they might want the theme to be dark but just don't know how. We can only control the app, so we give them the option there. 

That being said there are 4 possibilities: 
The first 2 are obvious because both the device and app match:
Device in light mode and app dark mode toggle off: use light theme.
Device in dark mode and app dark mode toggle on: use dark theme. 

If the device is in light mode and the app dark mode toggle is on, the user has deliberately turned dark mode on in the app - use a dark theme. 

If the device is in dark mode and the app dark mode toggle is off, we assume they did the device dark mode on purpose, so use a dark theme. 

That covers all the cases; there's no assumption we make if they just did a specific action.
